### ISSUE TITLE
Problem with Compression PDF files (The compression of a stream object)

### ISSUE THREAD

**Issue by mohamedDev** [highkite/pdfAnnotate#63]
Hello,
I have Problem with Compression PDF files (The compression of a stream object)
this becomes a problem, for me 

When i load PDF file, i have  this error on browser console
```
core.mjs:6495 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'compressed')
TypeError: Cannot read properties of undefined (reading 'compressed')
    at Function.extractObject (object-util.js:133:46)
    at Function.extract (parser.js:233:50)
    at PDFDocumentParser.extractAnnotations (parser.js:725:42)
    at AnnotationFactory._getAnnotations (annotation.js:468:42)
    at annotation.js:481:26
    at new ZoneAwarePromise (zone.js:1387:29)
    at AnnotationFactory.getAnnotations (annotation.js:480:16)

```
Can You help me please

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by gionnip** [comment]
Hi, any news about this issue? Thanks

**Comment by jjgriff93** [comment]
Also hitting this

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'compressed')
    at _ObjectUtil.extractObject (annotpdf.js?t=1728397791808&v=a8bf0c3b:5254:46)
    at Page.extractAnnotationArray (annotpdf.js?t=1728397791808&v=a8bf0c3b:16439:56)
    at Page.extract (annotpdf.js?t=1728397791808&v=a8bf0c3b:16455:18)
    at PDFDocumentParser.getPage (annotpdf.js?t=1728397791808&v=a8bf0c3b:16659:14)
    at _AnnotationFactory.createBaseAnnotation (annotpdf.js?t=1728397791808&v=a8bf0c3b:17373:38)
    at _AnnotationFactory.createHighlightAnnotation (annotpdf.js?t=1728397791808&v=a8bf0c3b:17412:43)
```
